apiVersion: kustomize.toolkit.fluxcd.io/v1
kind: Kustomization
metadata:
  name: gitops-multi
  namespace: flux-system
spec:
  interval: 1m0s
  path: ./apps
  prune: false
  sourceRef:
    kind: GitRepository
    name: gitops-multi
    namespace: flux-system